name: Deploy demo page

on:
  push:
    branches:
      - main # Replace with the branch you want to deploy from

jobs:
  start-server:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Start Python HTTP Server
      - name: Start Python HTTP Server
        run: |
          sudo apt-get update
          sudo apt-get install -y python3
          python3 -m http.server 80
